name: Java CI/CD with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        node-version: lts/Hydrogen
        
    - uses: actions/checkout@v2
    - run: |
        touch ./.env
        echo "${{ secrets.ENV }}" > ./.env
      
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/github-action-react .

    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Hub Push Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/github-action-react
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Excute Remote SSH Commands Using SSH_PRIVATE_KEY
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker pull dockerlecture/github-action-react
            docker run -d -p 8080:8080 --network=my-network --name github-action-frontend dockerlecture/github-action-react
            docker system prune -f
